### PR TITLE
Add new languages support for code block

### PR DESCRIPTION
**Pull request by ldez**
- Mustache
- OCaml
- Scala
- Groovy
- JSX

### CODE REVIEW

**Comment by mojavelinux** [comment]
Groovy!

**Comment by nicorikken** [comment]
As I recently played with Jenkinsfiles, I know the Jenkinsfile syntax is currently best handled by the Groovy language. It is also available as a supported filetype in the Groovy language grammar:

```
'fileTypes': [
  'groovy'
  'gvy'
  'gradle'
  'Jenkinsfile'
]
```

What do you think? Do we need a special language defined, currently handled by the Groovy syntax? (I could imagine such a thing, just like Ansible syntax is a variant of the YAML syntax and up until recently no dedicated Ansible parser was available) or do you want two match-options for the Groovy syntax like `(groovy|jenkinsfile)`?

**Comment by ldez** [comment]
Note if you add `jenkinsfile` to block it's not render properly (in Github but also others rendering tools)

- Groovy

```groovy
class AGroovyBean {
  String color
}

def myGroovyBean = new AGroovyBean()

myGroovyBean.setColor('baby blue')
assert myGroovyBean.getColor() == 'baby blue'

myGroovyBean.color = 'pewter'
assert myGroovyBean.color == 'pewter'
```

- Jenkinsfile

```jenkinsfile
class AGroovyBean {
  String color
}

def myGroovyBean = new AGroovyBean()

myGroovyBean.setColor('baby blue')
assert myGroovyBean.getColor() == 'baby blue'

myGroovyBean.color = 'pewter'
assert myGroovyBean.color == 'pewter'
```

**Comment by ldez** [comment]
Add custom markers, create a gap between editor and rendering tools, I think we must stay the more possible near of rendering tools.

**Comment by nicorikken** [comment]
Agreed, so we give each language a different parser, although sometimes the best parser might be used for some other language as well. Then this one can be merged. Even though I I might add some more language in the future then 😉

**Pull request merged**
