### PR TITLE
chore: continuous delivery

### PR DESCRIPTION
**Pull request by ldez**
@mojavelinux 

Edit `publish.sh`:
- `USER_EMAIL`: use to Git author
- `USER_NAME` : use to Git author
- `$encrypted_key`: rename this variable
- `$encrypted_iv`: rename this variable

In Travis CI UI define:
- `ATOM_ACCESS_TOKEN` with the Atom token

### CODE REVIEW

**Comment by nicorikken** [comment]
Does this imply that every merged PR is released as a new version? Because that does require complete PR's, which we just recently solved using the `WIP` and `ready` labels. Code looks good, I assume you did the right thing here. @mojavelinux can you make the final call on this one?

**Comment by ldez** [comment]
@nicorikken you are right: every merged PR is released as a new patch version by default.

I added documentation :wink:

**Comment by ldez** [comment]
The publishing system works when a commit is pushed on master.
The publishing system does not publish if you publish manually (git tag detection).

**Comment by nicorikken** [comment]
I am new to Travis' concept of environment variables, but going from the documentation [on Travis](https://docs.travis-ci.com/user/environment-variables/) does a merge now requires a change in the `.travis.yml` file to set the type of release (major/minor/patch)?

**Comment by ldez** [comment]
:smile_cat: bad section in the page, see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by ldez** [comment]
No changes  in the `.travis.yml` file required for nothing.
We never change this file.
We simply use an UI see https://travis-ci.org/asciidoctor/atom-language-asciidoc/settings

**Comment by ldez** [comment]
I added the web UI url to the documentation.

**Comment by mojavelinux** [comment]
I'll give it a shot and let you know if I run into any problems.

**Comment by mojavelinux** [comment]
@ldez Can you add asciidoctor-docbot to the package on atom.io? I just setup the account there.

**Comment by ldez** [comment]
I don't understand. You have created an account on Atom.io for the asciidoctor-docbot ?
If you have doing this, you have an Atom token.

**Comment by ldez** [comment]
For authorize the bot to publish, you must give it write access to this repository.

**Comment by mojavelinux** [comment]
Oh, I get it. I thought atom.io itself had to grant permissions. I didn't realize it was linked to GitHub auth.

**Comment by mojavelinux** [comment]
Am I correct that the RSA key should have no passphrase?

**Comment by ldez** [comment]
yes

**Comment by mojavelinux** [comment]
I sent a PR to your branch with the encrypted key and related configuration. I also added the Atom token to the build via the Travis CI web UI. I think we're good to go.

Do I need to keep the unencrypted RSA secret key?

**Comment by mojavelinux** [comment]
I guess merging this pull request is the moment of truth!

**Comment by ldez** [comment]
not needed.

And yes !!!!!!!! :tada:

**Comment by ldez** [comment]
AppVeyor is slow, very very slow...

**Pull request merged**
