### PR TITLE
doc: compatibility mode informations

### PR DESCRIPTION
**Pull request by ldez**
Add compatibility mode informations to the main readme.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'd like to have a chance to tune this statement. It's very important that we phrase this carefully because it's a sensitive issue.

**Comment by ldez** [comment]
Ok I close this PR and lets you create an another.

**Comment by mojavelinux** [comment]
You can keep it open. I'm just going to send a PR to your PR :)

**Comment by nicorikken** [comment]
Nice clear language, showing some ambition as well 🏆 👍

**Pull request merged**
