### PR TITLE
refactor: languages support

### PR DESCRIPTION
**Pull request by ldez**
- review regex
- add `name` attribute
- asciidoctor syntax and mardown syntax
- add SASS support
- fix several language bug
- **add AsciiDoctor comment support**

### CODE REVIEW

**Comment by nicorikken** [comment]
You know PRs are serious when GitHub's UI is giving up :+1:  I'll have a look.

**Comment by nicorikken** [comment]
@ldez Can I conclude the previous regexes were case-sensitive and you fixed that? And by referencing the block start in the end, you force the regex to work on balanced block separators only?

**Comment by ldez** [comment]
Yes your conclusion are good.
I also permit to add space before code block.

**Comment by ldez** [comment]
The main feature is the `name` attribute: allow to add asciidoctor comment scope.

**Comment by nicorikken** [comment]
So this implies that adding `// comment` in a code block will not influence the highlighting within the code block? (preparing for future feature in this way)

**Comment by ldez** [comment]
Not really: now you can press `ctrl+shift+/` in an AsciiDoctor document for comment a line.
And with the attribute `name` I can exclude that pressing those keys add a AsciiDoctor comment style in code block.
Comment in code block respect specific language comment style.

**Comment by nicorikken** [comment]
Doing a simple check on the effect of commenting inside code blocks, it seems that the commenting conforms to the language present in the code block. Testing inside an `[source, sh]` block triggers a `#` comment rather than a `//` comment. Am I missing the point?

**Comment by ldez** [comment]
It's a misunderstood of my part: the descriptor, in `settings/asciidoc.cson` with `not` part, affect `softWrap` option but not the comment scope.

**Comment by ldez** [comment]
I've made a language sample document, do you want I had this file to the project?

**Comment by nicorikken** [comment]
Sample document as in a .adoc file, or in specs. Either way including them will help. When including in tests, we need to watch out for the reduced language support in say travis, contrary to our massive Atom setups which presumably support some exotic languages.

**Comment by ldez** [comment]
I've added the file.
You can see some languages support bug, but I think it's a related to others languages plugins bugs.

**Comment by nicorikken** [comment]
Oh my, nice one! I count and can confirm 3 bugs, in Properties, PHP, and CSS. It seems that not all styles were converted to include `.embedded.` Is this due to rendering issues? To me this seems mergeable.

**Comment by mojavelinux** [comment]
:+1:

**Comment by nicorikken** [comment]
Thanks @ldez  I have merged this wonderful commit. @mojavelinux I've kept both separate commits, as they contribute distinct features (the refactor and the test/doc).

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
