### PR TITLE
refactor: remove snippets

### PR DESCRIPTION
**Pull request by ldez**
Remove snippets beginning with a letter.

Those snippets are now in [autocomplete-asciidoc](https://atom.io/packages/autocomplete-asciidoc)

### CODE REVIEW

**Comment by mojavelinux** [comment]
Why not move all the snippets to the new package?

**Comment by ldez** [comment]
I did not know what was best.
I can move all snippets if you think it's a good idea.

**Comment by mojavelinux** [comment]
I would say that they either belong together, or we should have the snippets in a separate atom-asciidoc-snippets package. I don't think it makes sense to have the snippets split across two packages.

**Comment by ldez** [comment]
I agree

**Comment by ldez** [comment]
I have removed the whole file.

**Pull request merged**
