### PR TITLE
Split various block

### PR DESCRIPTION
**Pull request by ldez**
Just split `blocks/various-block-grammar.cson` in multiple grammar files and tests.

- fix: wrong reference to `inlines` repositories patterns.

### CODE REVIEW

**Comment by nicorikken** [comment]
Nice refactoring work! Any objections to a merge?

**Comment by ldez** [comment]
Merge and release ? :wink:

**Comment by ldez** [comment]
Quote style before:

capture du 2016-05-02 22-05-40

and after:

capture du 2016-05-02 22-05-54

**Comment by nicorikken** [comment]
Merge for sure, release seems fair as it fixes a number of bugs.
Just out of curiosity, how long have you been using Asciidoc? Because your work goes into areas I didn't know existed in the language definitions.

**Comment by ldez** [comment]
Not so long, some months, I have read:
- AsciiDoctor code and when I found a new thing : I code
- AsciiDoctor documentation and... I code !

I'm a regular expressions lover's :smile:

**Pull request merged**
