### PR TITLE
AppVeyor configuration

### PR DESCRIPTION
**Pull request by ldez**
Add configuration file for [AppVeyor](https://ci.appveyor.com)

It's a free CI tool dedicate to Windows environment.

@mojavelinux can you activated the build on [AppVeyor](https://ci.appveyor.com) ?

Take the badge code on [badges page](https://ci.appveyor.com/project/asciidoctoratom-language-asciidocr/settings/badges), I would add the badge to this PR.

### CODE REVIEW

**Comment by nicorikken** [comment]
Despite my personal dislike for Windows, this is a good addition for the project, because Atom is so multi-target. 👍

**Comment by mojavelinux** [comment]
Yes, indeed! I'll take care of setting it up.

**Comment by ldez** [comment]
Any news ?

**Comment by mojavelinux** [comment]
First we need to merge. I'll do that, then proceed with the setup.

**Comment by mojavelinux** [comment]
> Despite my personal dislike for Windows...

Same here, but we do it for our users. It's them to whom we are giving :heart:.

**Comment by mojavelinux** [comment]
Voila !

https://ci.appveyor.com/project/asciidoctor/atom-language-asciidoc

**Comment by ldez** [comment]
@mojavelinux can you provide the badge ? [badges page](https://ci.appveyor.com/project/asciidoctoratom-language-asciidocr/settings/badges)

It's not like Travis, it's link with a hash.

**Comment by mojavelinux** [comment]
Yep! I'll do it.

**Pull request merged**
