### PR TITLE
fix: correction for respect CoffeeLint

### PR DESCRIPTION
**Pull request by ldez**

### CODE REVIEW

**Comment by nicorikken** [comment]
@ldez I fail to see the need for this commit. What does it fix? I guess it prevents an unnecessary level of nesting in the patterns. Could you elaborate?

**Comment by ldez** [comment]
It's simply for respect the rules defined in https://github.com/asciidoctor/atom-language-asciidoc/blob/master/coffeelint.json.

**Comment by nicorikken** [comment]
I'm all new to Coffeescript. Running the Coffeelint for the coffeelint.json does indeed return an error:
```
coffeelint -f coffeelint.json spec/asciidoc-spec.coffee
  ✗ spec/asciidoc-spec.coffee
     ✗ #209: a space is required after commas.

✗ Lint! » 1 error and 0 warnings in 1 file
```
However, your fix doesn't seem to resolve this error. Am I testing this the wrong way?

**Comment by mojavelinux** [comment]
> However, your fix doesn't seem to resolve this error. 

That seems to be a separate issue.

I think we should move forward with merging this change and dealing with the existing warning separately.

**Comment by ldez** [comment]
I've fixed the warning.

**Comment by mojavelinux** [comment]
Thanks!

:+1: to merge.

**Comment by nicorikken** [comment]
@ldez that was obvious, should have found that out myself. I'll do a final check and merge when I get back at my laptop.

**Comment by ldez** [comment]
Run the following command to see what I've fxed:

```shell
coffeelint -f coffeelint.json grammars/asciidoc.cson
```
```shell

Error - Curly braces must have the proper spacing. There should be 0 spaces inside "{". (braces_spacing)at line 84 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "}". (braces_spacing)at line 84 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "{". (braces_spacing)at line 102 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "}". (braces_spacing)at line 102 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "{". (braces_spacing)at line 118 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "}". (braces_spacing)at line 118 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "{". (braces_spacing)at line 183 col 7
Error - Curly braces must have the proper spacing. There should be 0 spaces inside "}". (braces_spacing)at line 183 col 7
```

I use https://atom.io/packages/linter-coffeelint for simplest reporting.

**Comment by nicorikken** [comment]
@ldez Thanks for the contribution, it has just been merged. Using the coffeelint definitions for checking should be a standard practice. Maybe we can included this in a CONTRIBUTING file.

**Comment by mojavelinux** [comment]
:+1:

**Comment by ldez** [comment]
I make a PR #52 for automatically run CoffeeLint on PR. :smiley:

**Pull request merged**
