### PR TITLE
add AppVeyor badge to README

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by ldez** [comment]
Can you restore the build on pull request ?

**Comment by mojavelinux** [comment]
I'm pretty sure it's running on each pull request. I see a build for the PR I just sent.

See https://ci.appveyor.com/project/asciidoctor/atom-language-asciidoc/build/20

**Comment by ldez** [comment]
ok but it don't appear on PR like that: https://github.com/bwklein/asciidoc-image-helper/pull/21

**Comment by mojavelinux** [comment]
I think it's a sync problem between the appveyor.yml and the configuration on AppVeyor. I'll push a fix to see if that does it.

**Comment by mojavelinux** [comment]
I don't get what's going on. The exchange between GitHub and AppVeyor seems to be broken. Everything is configured correctly.

**Comment by mojavelinux** [comment]
I'm really confused.

**Comment by mojavelinux** [comment]
I know what it is. I need to give the bots access to this repository. face-palm!

**Comment by mojavelinux** [comment]
Bingo! Solved.

**Pull request merged**
