### PR TITLE
feat: sidebar, example, literal paragraphs

### LINKED ISSUE #157: Highlight block-level AsciiDoc inside example and sidebar blocks
## Description

The example and sidebar blocks are compound blocks, which means they support nested AsciiDoc content. Therefore, the language should descend into the block to match and highlight AsciiDoc syntax.

## Screenshots

In this screenshot, the block title and the literal block should be highlighted. It's good that the image block is highlighted, but the highlighting shouldn't be limited to just block macros.

example-block-screenshot

## Syntax example

```adoc
====
Example block text.

.This is a screenshot
image::screenshot.jpg[]

....
literal block
....
====
```

### PR DESCRIPTION
**Pull request by ldez**
## Description

- Highlight block-level AsciiDoc inside example and sidebar blocks 
- change bock title color
- change literal block color
- change block content color
- fix: source paragraph bug
- add comments for comment block

Fix #157 

## Syntax example

Literal paragraph
```adoc
[literal]
....
Daleks EXTERMINATE in monospace!
....
foo

[literal]
--
Daleks EXTERMINATE in monospace!
--
foo

[literal]
Daleks EXTERMINATE in monospace!
```

Sidebar paragraph
```adoc
[sidebar]
****
A multi-line *sidebar*.
****
foo

[sidebar]
--
A multi-line *sidebar*.
--
foo

[sidebar]
A multi-line *sidebar*.
```

Example paragraph
```adoc
[example]
====
A multi-line *example*.
====
foobar

[example]
--
A multi-line *example*.
--
foobar

[example]
A example *paragraph*
```

## Screenshots

Literal paragraph
capture du 2016-06-09 21-06-04

Sidebar paragraph
capture du 2016-06-09 21-06-19

Example paragraph
capture du 2016-06-09 21-06-30

### CODE REVIEW

**Comment by mojavelinux** [comment]
Most excellent!

Only one small thing. You can have a listing and source paragraph too.

```
[listing]
$ gem install asciidoctor

[source,ruby]
puts "hi"
```

**Comment by ldez** [comment]
Source paragraph already but I cannot use embedded code style in this case.

**Comment by mojavelinux** [comment]
I'm not too concerned about source paragraph. In fact, I kind of think of that as a bad practice. It's best to enclose the source code. A listing paragraph, that could go either way. I'm still inclined to recommend against using it.

**Comment by ldez** [comment]
done:

```adoc
[listing]
--
an open block listing.
--
foo

[listing]
a listing paragraph

foo
```

capture du 2016-06-10 00-27-08

**Pull request merged**
