### PR TITLE
Allow additional attributes to be defined on source block

### LINKED ISSUE #93: Allow additional attributes to be defined on source block
## Description

The source block should allow additional attributes (to follow the keyword "source" and the language name).

## Syntax example

The following is a valid source block:

```
[source,ruby,subs=attributes+]
----
source 'https://rubygems.org'
gem 'asciidoctor', '{latest-release}'
----
```

Another example is enabling line numbers:

```
[source,ruby,linenums]
----
puts "Hello, World!"
----
```

### PR DESCRIPTION
**Pull request by ldez**
capture du 2016-05-08 23-02-55

```adoc
[source,ruby,subs=attributes+]
----
source 'https://rubygems.org'
gem 'asciidoctor', '{latest-release}'
----
```

Fix #93

### CODE REVIEW

**Comment by ldez** [comment]
- Support for additional parameters in block name.
- Support for 'raw' listing block.

Before:
capture du 2016-05-08 23-32-30

After:
capture du 2016-05-08 23-30-02

**Comment by nicorikken** [comment]
(The paste-able syntax example is a nice touch)

**Comment by nicorikken** [comment]
Tested, code reviewed, looks good for merge.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
