### PR TITLE
add more information about how the grammar works and how it's processed

### PR DESCRIPTION
**Pull request by mojavelinux**
Added information I discovered about the grammar, how it works and how it's processed.

### CODE REVIEW

**Comment by nicorikken** [comment]
Nice! Ready to merge? I am.

**Comment by mojavelinux** [comment]
Yep!

**Comment by mojavelinux** [comment]
I'm excited that we finally got the to bottom of what is processing the language definition. That transparency will really help us move forward with confidence and debug problems when we run into them.

**Comment by nicorikken** [comment]
Certainly.

**Pull request merged**
