### PR TITLE
Grammar `link`, `sub`, `super` and more

### LINKED ISSUE #71: Regression related to bold syntax.
capture du 2016-04-29 12-03-17

see [spec/fixtures/asciidoctor-lang.adoc](https://github.com/asciidoctor/atom-language-asciidoc/blob/master/spec/fixtures/asciidoctor-lang.adoc)

### PR DESCRIPTION
**Pull request by ldez**
## Description

First, I wanted to fix `link` syntax:
- but for it work I must change `list` syntax
- and for `list` syntax works again I must change the `bold`/`strong` syntax.

Very hard work...

- fix: `link` support
- feat: add `super` and `sub` support
- feat: `xref` support
- feat: enhance `macro` support (`menu`, `link`, `image`, `kbd`, ...)
- feat: add horizontal rule and page break
- feat: callout list item support
- feat: ordered list with `arabic`, `loweralpha`, `upperalpha`, `lowerroman`, `upperroman`
- refactor: `list` syntax
- refactor: `strong` syntax ( remove multi-lines support)
- refactor: split inline grammars in multiple files
- refactor: split specs in multiple files
- fix: wrong less syntax
- and a **lot of tests**

## Screenshots

capture du 2016-04-30 17-41-47

## Syntax example

```adoc
a*non-bold*a, !*bold*?, \'*bold*:, .*bold*; ,*bold*
* *dsq* dsq
* dsq* dsq

foobar
foobar~note~ foobar
foobar
foobar^25^ foobar
foobar
foobar

foobar <<id,reftext>> foobar
foobar xref:id[reftext] foobar

http://dksjdl

* http://dksjdl

https://dkslqlmd

ftp://dkslmq.dlsqm

irc://lkdmsq

link:path[label]

mailto:doc.writer@example.com[]

Go on link:url[optional link text, optional target attribute, optional role attribute] now

link:http://url[optional link text, optional target attribute, optional role attribute]

link:url[optional link text, optional target attribute, optional role attribute]

link:view-source:asciidoctor.org[Asciidoctor homepage, window="_blank"].

http://discuss.asciidoctor.org/[*mailing list*^, role="green"]

link:external.html#livereload[LiveReload]

link:protocol.json[Open the JSON file]

menu:File[New...]

menu:View[Page Style > No Style]

menu:View[Page Style, No Style]
```

## Related issues

Fix #71, #41, #31, #28, #9, #66, #37

### CODE REVIEW

**Comment by ldez** [comment]
After you merge this PR, can you create a release because `bold`/`strong` is a very annoying regression.

**Comment by nicorikken** [comment]
Quite extensive restructure, nice work! I'm eager to improve the bold highlighter instead of reverting back to the old one. I wanna pick up on that. I'll get back on the rest of the changes.

**Comment by ldez** [comment]
I'm nor revert to old, I use the original regex from Asciidoctor

**Comment by ldez** [comment]
I think you can merge this PR only to make a quick patch release and after you will fix support for `strong` multi-lines.
The regular expression I have use for `strong`, fix all current bug but not support multi-line.

**Comment by nicorikken** [comment]
I mistakenly concluded it was the old regex. Glad you rewrote it. Digging into the strong regex, it seems that some edge cases still fail. Granted, I should add some tests to ease development, and the horizontal rule would benefit from having a separate regex.
screen shot 2016-05-01 at 10 17 15
screen shot 2016-05-01 at 10 15 46

I'll probably be able to look into the other parts later today. Maybe we can include the changes in supported file formats as well.

**Comment by ldez** [comment]
I add horizontal rule and page break support.

**Comment by ldez** [comment]
It's better ?

capture du 2016-05-01 15-06-04
capture du 2016-05-01 15-08-27
capture du 2016-05-01 15-08-36




```
The three bullets bellow should form a horizontal line:

***

And starting from a space? -> also

 ***

0 *bold* 1 **bold* 2 ***bold* 3 * 4 ***bold** 5 ***bold*** 6 **bold*** 7 *bold***
  [c   ]   [uc        ][c   ]       [uc     ]   [uc     ]    [uc    ]    [c   ]

If we see that without multi-lines support, all this lines are good :

**b*old** 

***bold**

**b*old***

**bold* **

*bold**
```

**Comment by ldez** [comment]
A bonus:

capture du 2016-05-01 20-13-06

```asciidoc
[source, js]
----
var http = require('http'); <1>
http.createServer(function (req, res) { <2>
  res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
----
<1> *Grammars* _definition_
<2> *CoffeeLint* _rules_
```

**Comment by nicorikken** [comment]
Very nice! You did a lot of heavy lifting, again :+1: Regarding the bold highlighting (my pet project it seems) the Asciidoc preview shows the ability to nest strong matches, as shown in the included screenshot. I'd have to look into the details of the Asciidoctor.rb to see how the nesting is handled (enabling all inline, or just bold). Simply adding the '#inline' pattern doesn't resolve this issue.
screen shot 2016-05-01 at 22 37 02
But the bottom line is that your current work seems good for a merge.

A side-note: triggering the grammar rendering on my machine doesn't work. How can I debug this feature, to see what is going wrong?

**Comment by ldez** [comment]
If you can code ie `.coffee` file you must  press `ctrl+alt+R` for loading the code change.
After you must generate the grammar `ctrl+shift+P` and `ag`.

**Comment by ldez** [comment]
For debug press `ctrl+shift+I` and use break points.

**Comment by ldez** [comment]
I read this before doing : https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor.rb#L1157-L1166.

For me, the section `4` cannot be render as `constrained strong` with nested `unconstrained strong` because `unconstrained strong` is evaluate before `constrained strong`.

I have see the same thing as you with AsciiDoctor Preview but I can explain that.
If I use regulars expressions from AsciiDoctor code and if I apply them with the ordering in the documentation it's not possible. I don't understand if it's a bug with the package or a real rule.

**Comment by nicorikken** [comment]
I'll have to look into the debugging features, but for now I have been able to find a workaround for the grammar compilation. Removing the `'window:reload'` command from `main.coffee` does the job nicely. At least this allowed me to verify your generated grammar corresponds to the source definitions. With that in mind I'll merge this.

This discussion on bold highlighting, and multi-line and nesting in general seems valuable for future improvements. This can be included in a separate issue.

**Comment by ldez** [comment]
Can you make a release ?

The previous 'bold bug' is a blocking issue for me.

**Comment by Mogztter** [comment]
Looking forward to this new version! Awesome work :+1:

**Comment by ProgramFan** [comment]
Great work 👍 💯

**Comment by nicorikken** [comment]
@Mogztter @ProgramFan Thanks to you as well, for filing issues and contributing fixes. Now we need to iron out all the little details, and find a good (the best?) approach for handling multi-line parsing.

**Pull request merged**
